[platformio]
extra_configs = secrets.ini
; Por defecto, si le das al tick, compila y sube por OTA
default_envs = esp32_ota 

[env] ; Configuración BASE compartida para todos
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
  adafruit/Adafruit GFX Library @ ^1.11.9
  adafruit/Adafruit SH110X @ ^2.1.10
  ESP32Ping

[env:esp32_usb]
; Este perfil hereda la base y usa el cable clásico automáticamente

[env:esp32_ota]
; Este perfil hereda la base y además inyecta por red
upload_protocol = espota
upload_port = 192.168.1.101