[platformio]
extra_configs = secrets.ini
; Por defecto, si le das al tick, compila y sube por OTA
default_envs = esp32_usb
;default_envs = esp32_ota


[env] ; Configuración BASE compartida para todos
platform = espressif32
board = esp32dev
extra_scripts = pre_upload.py
framework = arduino
monitor_speed = 115200
; Silencia completamente los logs internos del SDK Espressif/IDF y del core Arduino.
; Sin esto, el WiFi stack, el netif, mDNS y ArduinoOTA vuelcan texto y binario por UART0.
;build_flags =
;  -DCORE_DEBUG_LEVEL=0
;  -DCONFIG_LOG_DEFAULT_LEVEL=0
;  -DLOG_LOCAL_LEVEL=ESP_LOG_NONE
;  -DCONFIG_LOG_MAXIMUM_LEVEL=0
lib_deps =
  adafruit/Adafruit GFX Library @ ^1.11.9
  adafruit/Adafruit SH110X @ ^2.1.10
  ESP32Ping

[env:esp32_usb]
; Este perfil hereda la base y usa el cable clásico automáticamente

[env:PROD_ota]
; Este perfil hereda la base y además inyecta por red
upload_protocol = espota
upload_port = 192.168.1.101
upload_flags =
    --auth=${secrets.ota_password}
[env:TEST_ota]
; Este perfil hereda la base y además inyecta por red
upload_protocol = espota
upload_port = 192.168.1.103
upload_flags =
    --auth=${secrets.ota_password}